apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{namespace}"
  name: "{app-name}"
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{app-name}"
  template:
    metadata:
      labels:
        app: "{app-name}"
    spec:
      containers:
        - name: "{app-name}"
          image: jksahani/web01:{Build.BuildId}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: "{namespace}"
  name: "{servicename}"
  labels:
    app: "{app-name}"
spec:
  type: LoadBalancer
  selector:
    app: "{app-name}"
  ports:
    - port: 80
      targetPort: 80